name: 'Jira Telegram'
description: 'Link Jira tickets without compromising Pull Request Titles.'
author: 'therynamo'
# inputs:
#   milliseconds: # change this
#     required: true
#     description: 'input description here'
#     default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
